sudo: required
services:
  - docker

before_install:
  - docker build -t meole/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run meole/react-test npm test -- --coverage

after_success:
  - docker build -t meole/multi-client ./client
  - docker build -t meole/multi-nginx ./nginx
  - docker build -t meole/multi-server ./server
  - docker build -t meole/multi-worker ./worker

# Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push meole/multi-client
  - docker push meole/multi-nginx
  - docker push meole/multi-server
  - docker push meole/multi-worker
